# Generated by Django 5.0.2 on 2024-03-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_doctorregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorregister',
            name='cntry',
            field=models.CharField(default='timezone.now', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctorregister',
            name='exp',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctorregister',
            name='spec',
            field=models.CharField(default='ghjg', max_length=100),
            preserve_default=False,
        ),
    ]
