# Generated by Django 5.0.2 on 2024-03-19 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_doctorregister_cntry_doctorregister_exp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorregister',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_images/'),
        ),
    ]
