# Generated by Django 5.0.2 on 2024-03-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_doctorregister_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorregister',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='app/static/docimage'),
        ),
    ]
