# Generated by Django 5.0.2 on 2024-03-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_doctorregister_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorregister',
            name='desc',
            field=models.TextField(default='exit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctorregister',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='docimage'),
        ),
    ]
