# Generated by Django 5.0.2 on 2024-03-22 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_register_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='height',
            field=models.CharField(default=170, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='register',
            name='weight',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
    ]
